---
name: Scan Image

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  scan-image:
    name: Scan Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Build Image
        id: build_image
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          push: false
          load: true
          tags: analytical-platform-kubectl

      - name: Scan Image
        id: scan_image
        uses: aquasecurity/trivy-action@f781cce5aab226378ee181d764ab90ea0be3cdd8 # v0.25.0
        with:
          image-ref: analytical-platform-kubectl
          exit-code: 1
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL
          limit-severities-for-sarif: true

      - name: Upload SARIF
        if: always()
        id: upload_sarif
        uses: github/codeql-action/upload-sarif@c36620d31ac7c881962c3d9dd939c40ec9434f2b # v3.26.12
        with:
          sarif_file: trivy-results.sarif

      - name: Scan Image (On SARIF Scan Failure)
        if: failure() && steps.scan_image.outcome == 'failure'
        id: scan_image_on_failure
        uses: aquasecurity/trivy-action@f781cce5aab226378ee181d764ab90ea0be3cdd8 # v0.25.0
        with:
          image-ref: analytical-platform-kubectl
          exit-code: 1
          format: table
          severity: CRITICAL
